// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aztgdohnqjlgobwwchoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dGdkb2hucWpsZ29id3djaG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODI3NjksImV4cCI6MjA2NjU1ODc2OX0.7sIuwtYSJ9gCuUE3AR2Ggu75RZ4HppuKX9q04baSavU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);